module Magic
	module Presenter
		module Generator
			private

			def      file_name: (?String name)                  -> String
			def      file_path: (?String path, ?root: Pathname) -> Pathname
			def presenter_path: (?String path)                  -> Pathname
		end
	end
end
