# frozen_string_literal: true

# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require 'combustion'

Combustion.initialize! :active_record,
		load_schema:    false,
		database_reset: false

Rails.application.load_tasks
