inherit_from:
  - https://github.com/Alexander-Senko/Alexander-Senko/raw/refs/heads/main/.rubocop.yml
  - https://github.com/Alexander-Senko/Alexander-Senko/raw/refs/heads/main/.rubocop-rails.yml
  - https://github.com/Alexander-Senko/Alexander-Senko/raw/refs/heads/main/.rubocop-rspec.yml

plugins:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  Exclude:
    - 'spec/internal/tmp/**/*'
