module Magic
	module Presenter
		VERSION: String

		def for:      (Class)  -> Class?
		def name_for: (Module) -> String
	end

	def each_engine: () { (Rails::Engine engine) -> void } -> Array[Rails::Engine]
			           | () -> Enumerator[Rails::Engine]
end
