module Magic
	module Presenter
		VERSION: String
		AUTHORS: Array[Gem::Author]

		def for:      (Class)  -> Class?
		def name_for: (Module) -> String
	end

	def eager_load: (*interned scopes) -> Array[Pathname]
end
