name: CI

on:
  push:
    branches:
      - main
    tags-ignore:
      - '*'
    paths:
      - lib/**
      - app/**
      - config/**
      - spec/**
      - Gemfile*
      - '*.gemspec'
      - .github/workflows/ci.yml
      - .rspec*
      - .rubocop*
      - '!**/version.rb'

  pull_request:
    paths-ignore:
      - '*.md'
      - '*.txt'
      - '**/version.rb'

jobs:
  lint:
    runs-on: ubuntu-latest

    env:
      BUNDLE_WITHOUT: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby (RubyGems)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ vars.RUBY_VERSION }}
          bundler:      none
      - name: Pre-install gems
        run:  gem install -N rubygems-author
        env:
          GEM_HOME: vendor/bundle/ruby/${{ vars.RUBY_VERSION }}.0
      - name: Set up Ruby (Bundler)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version:  ${{ vars.RUBY_VERSION }}
          bundler-cache: true
          rubygems:      default # skip

      - name: Lint code for consistent style
        run:  bin/rubocop -f github

  test:
    runs-on: ubuntu-latest
    name:    Ruby ${{ matrix.ruby }}, Rails ${{ matrix.rails }}
    strategy:
      matrix:
        ruby:
          - 3.4
          - 3.3
          - 3.2

          - truffleruby
          - truffleruby-head

        rails:
          - 8.0
          - 7.2

        include:
          - { ruby: head, rails: head }

    env:
      RAILS_VERSION:  ${{ matrix.rails }}
      BUNDLE_WITHOUT: development

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby (RubyGems)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler:      none
      - name: Pre-install gems
        id:   pre-install
        run: |
          gem install -N rubygems-author
          gem info       rubygems-author |
              ruby -e 'puts $stdin.read.sub /\A(\S+) \((.+)\).*Installed at: (\S+).*\z/m, "\\3/gems/\\1-\\2"' |
              xargs -I {} echo RUBYLIB={}/lib >> $GITHUB_ENV
      - name: Set up Ruby (Bundler)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version:  ${{ matrix.ruby }}
          bundler-cache: true
          rubygems:      default # skip

      - name: Run specs with code coverage
        uses: paambaati/codeclimate-action@v9
        env:
          CC_TEST_REPORTER_ID: c0d55225dd080a6c275d1312813d3ed860fa93f6f2fc7a4d37a30c9d6b4e9418
        with:
          coverageCommand: bundle exec rake
        continue-on-error: ${{ matrix.allow-fail || false }}
        id: test

      - name: Test ${{ steps.test.outcome }}
        run: |
          ruby -v
          bin/rails -v
