name: CI

on:
  pull_request:
    paths-ignore:
      - '*.md'
      - '*.txt'

  push:
    branches: [ main ]
    tags-ignore:
      - '*'
    paths:
      - lib/**
      - app/**
      - config/**
      - spec/**
      - Gemfile*
      - '*.gemspec'
      - .github/workflows/ci.yml

jobs:
  lint:
    name: Ruby ${{ matrix.ruby }}

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - head
          - 3.3
          - 3.2

          - truffleruby
          - truffleruby-head

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - uses: paambaati/codeclimate-action@v9
        env:
          CC_TEST_REPORTER_ID: c0d55225dd080a6c275d1312813d3ed860fa93f6f2fc7a4d37a30c9d6b4e9418
        with:
          coverageCommand: bundle exec rake

      - name: Lint code for consistent style
        run: bin/rubocop -f github


