name: CI

on:
  push:
    branches:
      - main
    tags-ignore:
      - '*'
    paths:
      - lib/**
      - app/**
      - config/**
      - spec/**
      - Gemfile*
      - '*.gemspec'
      - .github/workflows/ci.yml
      - .rspec*
      - .rubocop*
      - '!**/version.rb'

  pull_request:
    paths-ignore:
      - '*.md'
      - '*.txt'
      - '**/version.rb'

permissions: read-all

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    env:
      BUNDLE_WITHOUT: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          submodules: true

      - name: Set up Ruby (RubyGems)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ vars.RUBY_VERSION }}
          bundler-cache: true

      - name: Lint code for consistent style
        run:  bin/rubocop -f github

  test:
    runs-on: ubuntu-latest
    name:    Ruby ${{ matrix.ruby }}, Rails ${{ matrix.rails }}
    permissions:
      contents: read
      id-token: write
    strategy:
      matrix:
        ruby:
          - 4.0
          - 3.4

          - truffleruby
          - truffleruby-head

        rails:
          - 8.1
          - 8.0
          - 7.2

        include:
          - { ruby: head, rails: head }

    env:
      RAILS_VERSION:  ${{ matrix.rails }}
      BUNDLE_WITHOUT: development

    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          submodules: true

      - name: Set up Ruby (RubyGems)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run specs with code coverage
        run: bundle exec rake
        continue-on-error: ${{ matrix.allow-fail || false }}
        id: test

      - name: Upload coverage to Qlty Cloud
        if:   ${{ matrix.ruby == 'head' && steps.test.outcome == 'success' }}
        uses: qltysh/qlty-action/coverage@v2
        with:
          oidc:   true
          files:  coverage/.resultset.json
          format: simplecov

      - name: Test ${{ steps.test.outcome }}
        run: |
          ruby -v
          bin/rails -v
