name: CI

on:
  push:
    branches:
      - main
    tags-ignore:
      - '*'
    paths:
      - lib/**
      - app/**
      - config/**
      - spec/**
      - Gemfile*
      - '*.gemspec'
      - .github/workflows/ci.yml
      - .rspec*
      - .rubocop*
      - '!**/version.rb'

  pull_request:
    paths-ignore:
      - '*.md'
      - '*.txt'
      - '**/version.rb'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: head
          bundler-cache: true

      - name: Lint code for consistent style
        run: bin/rubocop -f github

  test:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}, Rails ${{ matrix.rails }}
    strategy:
      matrix:
        ruby:
          - head
          - 3.3
          - 3.2

          - truffleruby-head

        rails:
          - head
          - 8.0
          - 7.2

        include:
          # TruffleRuby
          - { ruby: 'truffleruby', rails: '7.2', allow-fail: true }

          # JRuby
          #- { ruby: 'jruby',      rails: '7.2', allow-fail: true }
          #- { ruby: 'jruby-head', rails: '7.2', allow-fail: true }

        exclude:
          # TruffleRuby
          - { ruby: 'truffleruby-head', rails: 'head' }
          - { ruby: 'truffleruby-head', rails: '8.0' }

    env:
      RAILS_VERSION: "${{ matrix.rails }}"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version:  ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run specs with code coverage
        uses: paambaati/codeclimate-action@v9
        env:
          CC_TEST_REPORTER_ID: c0d55225dd080a6c275d1312813d3ed860fa93f6f2fc7a4d37a30c9d6b4e9418
        with:
          coverageCommand: bundle exec rake
        continue-on-error: ${{ matrix.allow-fail || false }}
        id: test

      - name: Test ${{ steps.test.outcome }}
        run: |
          ruby -v
          bin/rails -v
